CREATE DATABASE bewdproject1;

use bewdproject1;

CREATE TABLE works (
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	class VARCHAR(30) NOT NULL,
	assignmentname VARCHAR(50) NOT NULL,
	duedate VARCHAR(30),
    weighing VARCHAR(30),
	date TIMESTAMP
);

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);